### ISSUE TITLE
App not returning to foreground

### ISSUE THREAD

**Issue by juanamd** [ioddly/react-native-alarms#3]
I've followed the installation, and everything works fine, except that when the app is on the background and the alarm fires, the app remains in the background.
I can see that the alarm fires correctly as the log call inside the callback is executed, but nothing else happens. Code is using AlarmAndroid.RTC_WAKEUP.

Is this intended behaviour or am I missing something?

Currently using React Native 0.44. Tried both on emulator and real device with same result.

**Comment by upvalue** [comment]
Not intended, no. I have been using this to deliver notifications only, so it didn't occur to me to do that. I will see about adding an option to do that, possibly this week if I have time.

Thanks for letting me know.

**Comment by juanamd** [comment]
Oh, ok. I'm just getting started with React Native so was pulling my hair trying to understand why it failed haha.

Just to also let you know: If I set the alarm and close the app, then a couple of seconds after it should fire, an android message error appears instead. Something like "Unfortunately *app name* has stopped". 

Thanks for the quick reply.

**Comment by upvalue** [comment]
Alright, will look into that as well. Thanks.

Have you considered using react-native-push-notifications? Sending a notification when the alarm triggers will probably be more in line with what Android users expect, and if they click on any notification from your app, it'll open it.

I am not super familiar with Android or RN myself (was just writing this because I needed it), but my understanding is that WAKEUP refers to an alarm firing after the device has gone idle.

**Comment by juanamd** [comment]
Im building an alarm clock app and would like to offer a custom snooze screen, that's why the push notification approach is not ideal imo.
And yes, I also wondered about the meaning of waking up the device (does it mean just start the app in the background or actually bringing it to the foreground?) but i found a stackoverflow topic about native android development where someone wanted to use RTC_WAKEUP without opening the app, so I deduce that opening the app is the default behaviour.

**Comment by upvalue** [comment]
Juan, I've changed things around a bit and tried to make the interface less hairy (see the README). The only breaking change (I *think!*) is that BootLauncher will no longer launch the app, rather it'll fire a @ boot event which can be used to restore alarms across device boots without launching the app.

I've added a launchMainActivity() method which should provide the functionality you want. You should call it when your alarm event fires.

I think I've fixed the crash issue.

Let me know if this works for you.

**Comment by juanamd** [comment]
Ok, i'll test this version and report back.
Thanks so much for the quick support and replies!

**Comment by juanamd** [comment]
So I tested it, and it works beautifully, except if I close the app. Then the event callback is never fired. Is there something to be done about this use case?

**Comment by upvalue** [comment]
I think we're at the limit of what can be done with alarms here. Sorry about the misleading note -- it does seem like they keep firing within a couple seconds of closing, which is why it was crashing, but I don't think they will actually persist for long.
