### ISSUE TITLE
alarmSetElapsedRealtimeWakeup crashing on Expo app sdk 29

### ISSUE THREAD

**Issue by mikeumus** [ioddly/react-native-alarms#5]
Getting the "Unfortunately, this app has stopped" dialog as the app crashes when using `alarmSetElapsedRealtimeWakeup` as well as the other alarms types:

![react-native-alarm-crash](https://user-images.githubusercontent.com/57934/43699115-6aa7294e-991b-11e8-82ec-0e8a33b4685b.gif)

Here's the repo:
 - https://github.com/mikeumus/lucid-timer/blob/react-native-alarms_init/App.js#L49

Thanks for any insights.

**Comment by upvalue** [comment]
Hi Mike,

This library is no longer maintained. It's possible that internal RN changes have introduced the error.

As I recall though, Expo doesn't support third-party native code?

**Comment by mikeumus** [comment]
Hi @ioddly, alright good to know. 

Yeah, it's an detached/ejected Expo app.

**Comment by mikeumus** [comment]
Related to https://github.com/expo/expo/issues/206

This library is ☠️for Expo 29+
